
package introsde.project.data.local.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserInterface", targetNamespace = "http://soap.local.data.project.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserInterface {


    /**
     * 
     * @param person
     * @return
     *     returns introsde.project.data.local.soap.Person
     */
    @WebMethod
    @WebResult(name = "Person", targetNamespace = "")
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://soap.local.data.project.introsde/", className = "introsde.project.data.local.soap.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://soap.local.data.project.introsde/", className = "introsde.project.data.local.soap.AddPersonResponse")
    @Action(input = "http://soap.local.data.project.introsde/UserInterface/addPersonRequest", output = "http://soap.local.data.project.introsde/UserInterface/addPersonResponse")
    public Person addPerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param username
     * @return
     *     returns introsde.project.data.local.soap.Person
     */
    @WebMethod
    @WebResult(name = "Person", targetNamespace = "")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://soap.local.data.project.introsde/", className = "introsde.project.data.local.soap.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://soap.local.data.project.introsde/", className = "introsde.project.data.local.soap.GetPersonResponse")
    @Action(input = "http://soap.local.data.project.introsde/UserInterface/getPersonRequest", output = "http://soap.local.data.project.introsde/UserInterface/getPersonResponse")
    public Person getPerson(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param token
     * @return
     *     returns introsde.project.data.local.soap.Person
     */
    @WebMethod
    @WebResult(name = "Person", targetNamespace = "")
    @RequestWrapper(localName = "getPersonByToken", targetNamespace = "http://soap.local.data.project.introsde/", className = "introsde.project.data.local.soap.GetPersonByToken")
    @ResponseWrapper(localName = "getPersonByTokenResponse", targetNamespace = "http://soap.local.data.project.introsde/", className = "introsde.project.data.local.soap.GetPersonByTokenResponse")
    @Action(input = "http://soap.local.data.project.introsde/UserInterface/getPersonByTokenRequest", output = "http://soap.local.data.project.introsde/UserInterface/getPersonByTokenResponse")
    public Person getPersonByToken(
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.project.data.local.soap.Person>
     */
    @WebMethod
    @WebResult(name = "PersonList", targetNamespace = "")
    @RequestWrapper(localName = "getAllPerson", targetNamespace = "http://soap.local.data.project.introsde/", className = "introsde.project.data.local.soap.GetAllPerson")
    @ResponseWrapper(localName = "getAllPersonResponse", targetNamespace = "http://soap.local.data.project.introsde/", className = "introsde.project.data.local.soap.GetAllPersonResponse")
    @Action(input = "http://soap.local.data.project.introsde/UserInterface/getAllPersonRequest", output = "http://soap.local.data.project.introsde/UserInterface/getAllPersonResponse")
    public List<Person> getAllPerson();

    /**
     * 
     * @param person
     * @return
     *     returns introsde.project.data.local.soap.Person
     */
    @WebMethod
    @WebResult(name = "Person", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://soap.local.data.project.introsde/", className = "introsde.project.data.local.soap.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://soap.local.data.project.introsde/", className = "introsde.project.data.local.soap.UpdatePersonResponse")
    @Action(input = "http://soap.local.data.project.introsde/UserInterface/updatePersonRequest", output = "http://soap.local.data.project.introsde/UserInterface/updatePersonResponse")
    public Person updatePerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.project.data.local.soap.FoodType>
     */
    @WebMethod
    @WebResult(name = "FoodTypeList", targetNamespace = "")
    @RequestWrapper(localName = "getFoodTypes", targetNamespace = "http://soap.local.data.project.introsde/", className = "introsde.project.data.local.soap.GetFoodTypes")
    @ResponseWrapper(localName = "getFoodTypesResponse", targetNamespace = "http://soap.local.data.project.introsde/", className = "introsde.project.data.local.soap.GetFoodTypesResponse")
    @Action(input = "http://soap.local.data.project.introsde/UserInterface/getFoodTypesRequest", output = "http://soap.local.data.project.introsde/UserInterface/getFoodTypesResponse")
    public List<FoodType> getFoodTypes();

    /**
     * 
     * @return
     *     returns java.util.List<introsde.project.data.local.soap.MovieGen>
     */
    @WebMethod
    @WebResult(name = "MovieGenList", targetNamespace = "")
    @RequestWrapper(localName = "getMovieGens", targetNamespace = "http://soap.local.data.project.introsde/", className = "introsde.project.data.local.soap.GetMovieGens")
    @ResponseWrapper(localName = "getMovieGensResponse", targetNamespace = "http://soap.local.data.project.introsde/", className = "introsde.project.data.local.soap.GetMovieGensResponse")
    @Action(input = "http://soap.local.data.project.introsde/UserInterface/getMovieGensRequest", output = "http://soap.local.data.project.introsde/UserInterface/getMovieGensResponse")
    public List<MovieGen> getMovieGens();

}
