
package introsde.project.adopter.recombee.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecombeeImplService", targetNamespace = "http://soap.recombee.adopter.project.introsde/", wsdlLocation = "https://recombee-introsde-2018.herokuapp.com/ws/recombee?wsdl")
public class RecombeeImplService
    extends Service
{

    private final static URL RECOMBEEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECOMBEEIMPLSERVICE_EXCEPTION;
    private final static QName RECOMBEEIMPLSERVICE_QNAME = new QName("http://soap.recombee.adopter.project.introsde/", "RecombeeImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://recombee-introsde-2018.herokuapp.com/ws/recombee?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECOMBEEIMPLSERVICE_WSDL_LOCATION = url;
        RECOMBEEIMPLSERVICE_EXCEPTION = e;
    }

    public RecombeeImplService() {
        super(__getWsdlLocation(), RECOMBEEIMPLSERVICE_QNAME);
    }

    public RecombeeImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECOMBEEIMPLSERVICE_QNAME, features);
    }

    public RecombeeImplService(URL wsdlLocation) {
        super(wsdlLocation, RECOMBEEIMPLSERVICE_QNAME);
    }

    public RecombeeImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECOMBEEIMPLSERVICE_QNAME, features);
    }

    public RecombeeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecombeeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecombeeInterface
     */
    @WebEndpoint(name = "RecombeeImplPort")
    public RecombeeInterface getRecombeeImplPort() {
        return super.getPort(new QName("http://soap.recombee.adopter.project.introsde/", "RecombeeImplPort"), RecombeeInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecombeeInterface
     */
    @WebEndpoint(name = "RecombeeImplPort")
    public RecombeeInterface getRecombeeImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.recombee.adopter.project.introsde/", "RecombeeImplPort"), RecombeeInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECOMBEEIMPLSERVICE_EXCEPTION!= null) {
            throw RECOMBEEIMPLSERVICE_EXCEPTION;
        }
        return RECOMBEEIMPLSERVICE_WSDL_LOCATION;
    }

}
